name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build --if-present

      - name: Run security checks
        run: npm audit --audit-level=moderate || true

      - name: Check deployment secrets
        run: |
          if [ -z "${{ secrets.DEPLOY_HOST }}" ]; then
            echo "⚠️  Warning: DEPLOY_HOST secret not configured"
            echo "To enable deployment, add the following secrets in GitHub Settings:"
            echo "  - DEPLOY_HOST: Your deployment server host"
            echo "  - DEPLOY_USER: SSH username"
            echo "  - DEPLOY_KEY: SSH private key"
          fi

      - name: Create deployment artifact
        run: |
          mkdir -p deploy-package
          cp -r backend/ deploy-package/
          cp -r public/ deploy-package/ 2>/dev/null || true
          cp package.json package-lock.json deploy-package/
          tar -czf pelbiot-deploy-${{ github.sha }}.tar.gz deploy-package/
        continue-on-error: true

      - name: Archive deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package-${{ github.run_number }}
          path: pelbiot-deploy-${{ github.sha }}.tar.gz
        continue-on-error: true

      - name: Deploy to server (if secrets configured)
        if: secrets.DEPLOY_HOST != ''
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            echo "Deployment would start here"
        continue-on-error: true

            
            # Stop current application
            pm2 stop pelbiot || true
            
            # Download artifact
            wget -q https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/pelbiot-deploy-${{ github.sha }}.tar.gz
            
            # Extract and install
            tar -xzf pelbiot-deploy-${{ github.sha }}.tar.gz
            npm ci --production
            
            # Database migrations (if applicable)
            npm run migrate --if-present
            
            # Start application
            pm2 start ecosystem.config.js
            
            # Cleanup
            rm pelbiot-deploy-${{ github.sha }}.tar.gz

      - name: Health check
        run: |
          sleep 10
          curl -f http://${{ secrets.DEPLOY_HOST }}:3001/api/enhancements/health || exit 1

      - name: Create deployment status
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            github.rest.deployments.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ job.id }},
              state: '${{ job.status }}',
              environment_url: 'https://${{ secrets.DEPLOY_HOST }}',
              description: 'Deployment ${{ job.status }}'
            });

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'PELBIOT Deployment ${{ job.status }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          fields: repo,message,commit,author
